import type { Metadata } from "next";
import "./(main)/globals.css";

import { Providers } from "@/app/(main)/providers";
import { Toaster } from "@/components/ui/sonner";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
	title: { default: "Phantom Chat", template: "Phantom Chat | %s" },
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${GeistSans.variable} ${GeistMono.variable} antialiased relative overscroll-none font-mono`}
			>
				<Providers>
					{children}
					<Toaster mobileOffset={16} duration={2000} />
				</Providers>
			</body>
		</html>
	);
}
