import type { Metadata } from "next";
import "./globals.css";

import { ThemeSwitcher } from "@/components/theme-switcher";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Phantom Chat",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${GeistSans.variable} ${GeistMono.variable} antialiased relative overscroll-none`}
			>
				<Providers>
					{children}
					<ThemeSwitcher />
				</Providers>
			</body>
		</html>
	);
}
